#!/bin/bash
if [ $# != 1 ]
	then
	php gd_server.php restart -d
	php server.php restart -d
	exit 2
fi
if [ $1 == "start" ]
	then
	php gd_server.php start -d
	php server.php start -d
	elif [ $1 == "stop" ]
	then
	php server.php stop
	php gd_server.php stop
	elif [ $1 == "restart" ]
	then
	php gd_server.php restart -d
	php server.php restart -d
	elif [ $1 == "only" ]
	then
	php server.php restart -d
fi
